version: "3.1"
services:
    redis:
      image: redis:alpine
      container_name: getcuredsoon-redis
    postgres:
      env_file:
        - .env
      image: postgres:11.1-alpine
      container_name: getcuredsoon-postgres
      working_dir: /application
      volumes:
        - ../app:/application
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "8084:5432"
    webserver:
      image: nginx:alpine
      container_name: getcuredsoon-webserver
      working_dir: /application
      volumes:
          - ./app:/application
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
    php-fpm:
      build:
        context: .
        dockerfile: .docker/php-fpm/Dockerfile
      container_name: getcuredsoon-php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
