version: "3.7"
services:
    redis:
      image: redis:alpine
      container_name: getcuredsoon-redis
    postgres:
      env_file:
        - .env
      image: postgres:11.1-alpine
      container_name: getcuredsoon-postgres
      working_dir: /applicationr
      volumes:
        - ../app:/application
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "8084:5432"
    webserver:
      image: nginx:alpine
      container_name: getcuredsoon-webserver
      working_dir: /application
      volumes:
          - code:/application
          - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      depends_on:
        - php-fpm
    php-fpm:
      build:
        context: .
        dockerfile: .docker/php-fpm/Dockerfile
      container_name: getcuredsoon-php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - ./.docker/php-fpm/php-init-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - ./.docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      environment:
        - XDEBUG_MODE=${XDEBUG_MODE}
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
        paths:
          - 'vendor'
          - 'node_modules'
          - '.idea'
    code:
      alpha: '.'
      beta: 'volume://app'
      permissions:
        defaultDirectoryMode: 755
        defaultFileMode: 644
      configurationBeta:
        permissions:
          defaultOwner: 'id:33'
          defaultGroup: 'id:33'
volumes:
  code:
