name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: |
        cd app
        composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: app/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
  static-analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cd app
        composer install --prefer-dist --no-progress
    - name: PHPStan
      run: |
        cd app
        vendor/bin/phpstan -cphpstan.neon

    - name: Mess detector
      run: |
        cd app
        vendor/bin/phpmd src text cleancode, codesize, controversial, design, naming, unusedcode

    - name: Code sniffer
      run: |
        cd app
        vendor/bin/phpcs --standard=PSR12 src

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
